### ISSUE TITLE
Oslo/password doesn't work using sst in aws lambda

### ISSUE THREAD

**Issue by rifkyputra** [pilcrowOnPaper/oslo#73] opened 2024-05-16 12:53 UTC
<img width="1060" alt="image" src="https://github.com/pilcrowOnPaper/oslo/assets/11476083/9746f028-3b8c-4b3f-a0a0-079a6aea5fad">

can't deploy using `sst deploy`
neither `sst dev`

here's my code
```
import { Argon2id } from 'oslo/password'

const argon2id = new Argon2id()

export async function argon2Hash(password: string): Promise<string> {
  return await argon2id.hash(password)
}

export async function argon2Verify(password: string, hashedPassword: string): Promise<boolean> {
  return await argon2id.verify(hashedPassword, password)
}
```

**Comment by directormac** [comment] 2024-05-16 18:11
Refer to #74, i think we are all having same issues. there is a fix there i posted also at discord

**Comment by pilcrowonpaper** [comment] 2024-05-20 00:38
I think duplicate of #74 and the fix is in the issue/comment. Unfortunately little Oslo can do here since it's a bundler thing

**Closed as completed by pilcrowonpaper** 2024-05-20 00:38 UTC
